### PR TITLE
Refactor comments spec + controller fixes

### LINKED ISSUE #1823: Refactor spec/controllers/comment_controller_spec.rb to spec/request/comment_spec.rb
# Description

Controller Specs had been obsolete since Rails 5. It is best practice to create request spec instead of controller spec as recommended by the Rspec team.

Recommended Reading:

- [Stackoverflow Discussion in regards to Controller Specs vs Request Specs](https://stackoverflow.com/questions/40851705/controller-specs-vs-request-specs)
- [Medium article discussing request and controller specs](https://medium.com/just-tech/rspec-controller-or-request-specs-d93ef563ef11)

Resources on Request Spec formatting:

- [RelishApp](https://relishapp.com/rspec/rspec-rails/v/4-0/docs/request-specs/request-spec)

Original Issue: https://github.com/ifmeorg/ifme/issues/1815

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

### PR DESCRIPTION
**Pull request by tyler-wel**
# Description

The scope of the request spec refactor expanded by just a tad. 
- Refactored the original comment controller spec into comments request spec
- Expanded on the test cases to cover more of the controller logic
- Added failure to the controller where deletion has actually failed
  - Originally, if a comment failed to delete, the frontend had no idea and continued as normal

## More Details
One bigger change was made to the route. To me personally, I found it odd to have to do `comment_index_path` to get the path we wanted, especially since this route doesn't _actually have_ an index action. Because of this, I changed it to `comments`. This also is inline with most of the other routes

- comment_controller -> comments_controller
- paths are now called as `comments_path` and `delete_comments_path`
- changed all references of the existing paths to use the new pluralized form
- changed the action from destroy to delete

The reason this change was originally prompted was due to the following error while creating the request spec
```
ActionController::UrlGenerationError:
  No route matches {:action=>"destroy", :controller=>"comment"}, missing required keys: [:id]
```

## Corresponding Issue

fixes #1823 

---

Reviewing this pull request? Check out our [Code Review Practices](https://github.com/ifmeorg/ifme/wiki/Code-Review-Practices) guide if you haven't already!

### CODE REVIEW

File: config/routes.rb [hunk 1]
```diff
@@ -14,7 +14,7 @@
     end
   end
 
-  resources :comment, only: %i[create destroy] do
+  resources :comments, only: %i[create delete] do
```
Comment (julianguyen) [inline config/routes.rb:17]: Yesss 🙏

File: app/controllers/comments_controller.rb [hunk 2]
```diff
@@ -44,16 +45,21 @@ def handle_create(comment_params)
     comment.id
   end
 
+  # rubocop:disable Metrics/MethodLength
```
Comment (julianguyen) [inline app/controllers/comments_controller.rb:48]: It makes sense to add this and this is better than making unnecessary helpers for the sake of preventing Rubocop from complaining. I wonder long term if we should just disable "Metrics/MethodLength" in our general config. I don't see this as fundamental. I think PR reviews should help identify whether to reduce the size of a method.

It looks like there are some other places where `# rubocop:disable Metrics/MethodLength` is used (`# rubocop:disable Layout/LineLength` too). 

This can be tackled in another PR :) Let me know what you think!

**Review by julianguyen — APPROVED** [review]
Excellent work, thanks for going above and beyond to improve error handling and routing 🙌

File: app/controllers/comments_controller.rb (hunk 2 above)
Comment (tyler-wel) [reply app/controllers/comments_controller.rb:48]: Yaaa, I agree with this. I was staring at this method like.... how... how can I reduce this even more??? lol

10 lines just seems waaaay too short, and you'll end up having a ton of little unnecessary "helper" methods. 

I think adding a PR to adjust the rubocop rules would be good! Maybe either a new max like...35? 40? Or just remove it all together 🤔

Comment (julianguyen) [reply app/controllers/comments_controller.rb:48]: Good question. Yeah, maybe we could increase the max for now. Do you wanna take that on in another PR? :)

**Review by julianguyen — APPROVED** [review]

File: app/controllers/comments_controller.rb (hunk 2 above)
Comment (tyler-wel) [reply app/controllers/comments_controller.rb:48]: Ya sure :D

Comment (julianguyen) [reply app/controllers/comments_controller.rb:48]: Looks like we can remove these comments with your rubocop config changes merged!

File: spec/requests/comments_spec.rb [hunk 3]
```diff
@@ -0,0 +1,314 @@
...
+      let(:user) { create(:user) }
+
+      # Shared examples reduce repeated code
+      shared_examples_for 'a comment is not created' do
+
+        it { is_expected.to eq 400 }
+
+        it 'returns an empty comment' do
+          subject
+          expect(JSON.parse(response.body)).to eq({})
```
Comment (bennpham) [inline spec/requests/comments_spec.rb:24]:
```suggestion
          expect(JSON.parse(response.body)).to be_empty
```

Just a nitpick otherwise this is fine too.

**Review by bennpham — APPROVED** [review]
This looks great. Good job with fixing the routing 👍 👍 🐶 🐶 🐕

File: spec/requests/comments_spec.rb (hunk 3 above)
Comment (tyler-wel) [reply spec/requests/comments_spec.rb:24]: Ahhh good point 👍 if I get back to my PC before it's merged I'll fix it, it not maybe if I can do another rspec refactor i'll do it then... Or maybe we can do a like, once over refactor once all of the smaller issues are merged 🤔
