### PR TITLE
Fixes #1645

### LINKED ISSUE #1645: On resources page, focus changes incorrectly when tag is selected
I wasn't sure how to title this ticket...

When I go to [the resources page](https://www.if-me.org/resources), and have this view:

image

and I click the "hotlines" tag on the left, it works, but the focus/page immediately changes to this:

image

---

Please assign yourself (via the Assignees dropdown), if you do want to work on this issue. Can't find yourself? You need to [join our organization](https://github.com/ifmeorg/ifme/wiki/Join-Our-Slack).

Check out our [Picking Up Issues](https://github.com/ifmeorg/ifme/wiki/Picking-Up-Issues) guide if you haven't already!

### PR DESCRIPTION
**Pull request by Manasa2850**
@GayathriVenkatesh did most of it. I've helped her a bit.
Do let us know if we need to make any changes. Thanks!

Issue #1645

### CODE REVIEW

File: client/app/components/Resource/index.jsx [hunk 1]
```diff
@@ -14,12 +14,17 @@ type Props = {
...
+  window.scrollTo(0, 0);
+};
+
 const taggedResources = (
   tagged: ?boolean,
   tags: ?(string[]),
   updateTagFilter,
 ) => {
   if (tagged && tags) {
+    scrollUp();
```
Comment (julianguyen) [inline client/app/components/Resource/index.jsx]: So this will work when you click tags, but when you click the "Load More" button at the bottom of the page, it will unintentionally scroll back up.

You'll only want to call this when the `Tag` component is clicked. You'll want to do this in the `onClick` listener.
